### ISSUE TITLE
build fails on windows

### ISSUE THREAD

**Issue by logicfish** [BBasile/ircbod2#1]
```
$ dub run --root=AppData/Roaming/dub/packages/ircbod2-0.1.5/ircbod2/
Performing "debug" build using dmd for x86.
ircbod2 0.1.5: building configuration "library"...
C:\Users\Mark\AppData\Roaming\dub\packages\ircbod2-0.1.5\ircbod2\source\ircbod\stream.d(1645,39): Error: function core.sys.windows.winbase.GetFileSize (void*, uint*) is not callable using argument types (void*, const(uint)*)
dmd failed with exit code 1.

```

**Comment by BBasile** [comment]
Thanks, i don't hide that i don't use Windows much fortunately i still have a setup. Although PR welcome if you can fix it yourself. It might be an error made when i applied D-Scanner advices ([this commit](https://github.com/BBasile/ircbod2/commit/d396ed249fd1eb795f868baf9307d998cbf14e77)) in a `version(Windows){}` block.
